version: '3.8'
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
  python:
    image: python:3.10
    working_dir: /app
    volumes:
      - ./dmp-intellisense-source:/app
    command: bash -c "pip install poetry && poetry install && poetry run python run.py"
    environment:
      - OLLAMA_ENDPOINT=http://ollama:11434
    depends_on:
      - ollama
    ports:
      - "5001:5001"
  api:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "npm install && node app.js"
    environment:
      - PYTHON_BACKEND_URL=http://python:5001
    depends_on:
      - python
    ports:
      - "3001:3001"
  web:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "npm install && npm run dev"
    environment:
      - NEXT_PUBLIC_API_BASE=http://api:3001
    depends_on:
      - api
    ports:
      - "3000:3000"
