name: CI Python
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          cd dmp-intellisense-source
          poetry install
      - name: Run tests
        run: |
          cd dmp-intellisense-source
          poetry run pytest ../backend/tests
